from setuptools import setup, find_packages

setup(
    name="terminal-hacker-tools",
    version="0.1.0",
    description="Network scanning and password cracking tools for Terminal Hacker RPG",
    author="Terminal Hacker Team",
    author_email="contact@terminalhacker.com",
    packages=find_packages(),
    install_requires=[
        "aiohttp>=3.8.0",
        "asyncio>=3.4.3",
        "python-socketio>=5.0.0",
        "fastapi>=0.68.0",
        "uvicorn>=0.15.0",
        "pydantic>=1.8.0",
        "python-multipart>=0.0.5",
        "requests>=2.26.0",
        "python-dotenv>=0.19.0",
        "cryptography>=3.4.7",
        "numpy>=1.21.2",
        "scapy>=2.4.5",
        "colorama>=0.4.4",
        "tqdm>=4.62.3",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Games/Entertainment :: Simulation",
        "Topic :: Security",
    ],
) 